name: Test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write

    environment:
      name: github-pages
      url: ${{ steps.generate.outputs.page_url }}

    steps:
      - name: Generate Alteza Website
        id: generate
        # Improve a bit once https://github.com/orgs/community/discussions/10985 is implemented.
        uses: arjun-menon/alteza@master
        with:
          path: alteza/test_content
